apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: jinbing
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: 1520006273/yanxuan-node-demo:v1
            ports:
                - containerPort: 12000
