apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: demo01
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot
        source:
          git:
            url: https://github.com/stone-jin/knative-build-template.git
            revision: master
        template:
          name: buildpacks-cnb
          arguments:
          - name: IMAGE
            value: 1520006273/node-demo:v1
      revisionTemplate:
        spec:
          container:
            image: 1520006273/node-demo:v1
